# Generated by Django 5.1.4 on 2024-12-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('building', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=100)),
                ('campus', models.CharField(choices=[('Lý Thường Kiệt', 'Lý Thường Kiệt'), ('Dĩ An', 'Dĩ An')], max_length=50)),
                ('status', models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Vô hiệu hóa', 'Vô hiệu hóa'), ('Gặp sự cố', 'Gặp sự cố'), ('Hàng đợi đầy', 'Hàng đợi đầy')], default=('enabled', 'Enabled'), max_length=20)),
                ('total_pages_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('page_balance', models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('num_pages', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('no_copies', models.IntegerField()),
                ('page_sizes', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('A3', 'A3'), ('A5', 'A5'), ('Legal', 'Legal')], max_length=20)),
                ('one_sided', models.BooleanField()),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='base.printer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='base.student')),
            ],
        ),
    ]
